### ISSUE TITLE
Not showing memory when tab pinned

### ISSUE THREAD

**Issue by billysanca** [schomery/tab-memory-usage#1]
Firefox Nightly x64 in Windows 10.
When pin tab, memory usage disappears unlike in version 1.4.1.

![screenshot_1](https://cloud.githubusercontent.com/assets/5010722/9019415/8ee5c522-37c1-11e5-9ead-633d19c13be6.png)

**Comment by schomery** [comment]
That's right. I changed the way data is inserted in tabs. For the pin tabs you need to hover mouse over the tab and wait for the tooltip to be sohwn. In the current version, memory usage is appended to the title element. The old method was buggy, especially when you have many tabs opened.

**Comment by billysanca** [comment]
Thank you for the answer, @schomery.
But couldn't we have the option to choose between show or hide memory usage in those pinned tabs?

**Comment by schomery** [comment]
so in the new version, there is a new setting to allow user select whether they want the tab memory to be shown. I guess "Outside mode" will fix your problem, https://addons.mozilla.org/en-US/firefox/addon/tab-memory-usage/versions/
