### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by brettz9** [schomery/tab-memory-usage#10]
Hi,

I'd like to keep your add-on installed, but while doing some debugging on my own code, I keep getting console errors at this line:

https://addons.mozilla.org/en-US/firefox/files/browse/416133/file/lib/main.js#L144

Could you silently exit (or otherwise recover silently) if `node` is not present?

Thanks!

**Comment by schomery** [comment]
Thanks for the report. It is fixed now on 0.2.4b1
https://github.com/schomery/tab-memory-usage/blob/master/builds/jid1-fRvgLzKONCsPew@jetpack-0.2.4b1.xpi?raw=true

to try, download the XPI and drop it into your Firefox browser

**Comment by brettz9** [comment]
Thanks!
