### ISSUE TITLE
Multiple usage report on tabs

### ISSUE THREAD

**Issue by The-Prisoner** [schomery/tab-memory-usage#2]
Hello,

The previously fixed bug is again present in Firefox 40, checked with Linux Mint and Windows 7.
![bugmemorytab](https://cloud.githubusercontent.com/assets/13760431/9217685/156aa42a-40cb-11e5-805f-0ee3c5ce0e62.png)

Also, when I add a bookmark, the multiple usage report are displayed in the name.

**Comment by schomery** [comment]
Is this fixed?
https://github.com/schomery/tab-memory-usage/blob/master/src/executables/extension.xpi?raw=true

Just download the XPI and drop it into your Firefox browser. You need to restart once to get rid of the old reports though.

**Comment by The-Prisoner** [comment]
Yes it's fixed. Thanks

**Comment by ghost** [comment]
> Multiple usage report on tabs

![tmu](https://cloud.githubusercontent.com/assets/886325/11165309/da7f335e-8b0b-11e5-9a98-1b233f8454b7.png)

Happens when page changes title dynamically. Here, when I get new message.
http://www.wykop.pl/
Fx 43b3
