### ISSUE TITLE
Feature Request: Display memory usage info in the Addon bar

### ISSUE THREAD

**Issue by rchavik** [schomery/tab-memory-usage#4]
Personally, I would prefer if the memory usage is displayed in the Addon/status bar.

**Comment by rugk** [comment]
:+1:

**Comment by schomery** [comment]
I've just pushed a new update. In this version you can select "Toolbar mode" in which memory usage is displayed inside a badged toolbar button instead of the title-bar.
https://addons.mozilla.org/en-US/firefox/addon/tab-memory-usage/versions/

**Comment by rchavik** [comment]
Oh nice!

Thank you very much.

**Comment by rugk** [comment]
Okay, nice, but if you drag and drop the icon into the toolbar IMO the icon is still too big:
![toolbar](https://cloud.githubusercontent.com/assets/11966684/13554850/da62f77a-e3b2-11e5-927c-2f7b7e0ad80c.PNG)

I'd rather prefer a simple text view (and possibly only a small circle on the left of the text, which is coloured and shows the current state) and please add "MB" at the end. I don't like numbers without unities.

**Comment by rugk** [comment]
Especially when the memory usage is heigh (>= 100 MB) the number is not shows completely in the add-on bar, which does not really look nice:
![badicon](https://cloud.githubusercontent.com/assets/11966684/13604557/99e52cda-e543-11e5-8b90-ca8aaab4c273.PNG)

**Comment by rugk** [comment]
BTW in a new version it now looks much better:
![memory](https://cloud.githubusercontent.com/assets/11966684/14048504/ee0e1664-f2ae-11e5-8c21-511c36e2fdd8.PNG)

So thanks for the update, @schomery!
