### ISSUE TITLE
license for tab-memory-usage.

### ISSUE THREAD

**Issue by r5d** [schomery/tab-memory-usage#5]
Hey @schomery, I was wondering under what license tab-memory-usage is under.

If you've not licensed the code yet, I highly recommend that you to so. [According to GitHub's choosalicense.com](http://choosealicense.com/no-license/):

>  the absence of a license means that default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work.

See http://choosealicense.com/ and https://gnu.org/licenses/ for information that will help you choose the right license for your program.

Thank you.

**Comment by schomery** [comment]
I am publishing it under MPL 2.0
https://github.com/schomery/tab-memory-usage/blob/master/src/package.json#L7

Also added the license file to the root directory.

Thanks for the report.
