### ISSUE TITLE
Improve toolbar mode

### ISSUE THREAD

**Issue by rugk** [schomery/tab-memory-usage#8]
From https://github.com/schomery/tab-memory-usage/issues/4#issuecomment-192902237:

> Okay, nice, but if you drag and drop the icon into the toolbar IMO the icon is still too big:
> ![toolbar](https://cloud.githubusercontent.com/assets/11966684/13554850/da62f77a-e3b2-11e5-927c-2f7b7e0ad80c.PNG)
> 
> I'd rather prefer a simple text view (and possibly only a small circle on the left of the text, which is coloured and shows the current state) and please add "MB" at the end. I don't like numbers without unities.

and

> Especially when the memory usage is heigh (>= 100 MB) the number is not shown completely in the add-on bar, which does not really look nice:
> ![badicon](https://cloud.githubusercontent.com/assets/11966684/13604557/99e52cda-e543-11e5-8b90-ca8aaab4c273.PNG)

**Comment by vsiegel** [comment]
I see the same issue, just more severe - in most cases only 1 digit is shown, not two.

I noticed that the full number is shown more often - surprisinly - when I switch to small buttons in "Customize". It seems to work when the tooltip is too long to fit inside the button "anyway" (in some way).

**Comment by schomery** [comment]
I don't think there is any control over the ellipsis overflow. This is how the text is handled in the badged mode. Seems like text can have up to 3 chars. From next version I am striping decimal points to keep the text as small as possible; https://github.com/schomery/tab-memory-usage/commit/284951a166513f70eec0051dfee55eabd0db722d

Anyhow I am not sure how to fix this. Please reopen if you have found an extension that can handle these kinds of overflows. Meanwhile you can use "Toolbar -> Label" mode.
